name: diffusionerf
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - torchvision=0.13.1
  - ninja
  - trimesh
  - opencv=4.6.0
  - tensorboardX
  - pytorch-cuda=11.7
  - pytorch=1.12
  - numpy=1.23.3
  - pandas=1.5.0
  - tqdm
  - matplotlib=3.6.1
  - rich
  - packaging
  - scipy=1.9.1
  - pip
  - pip:
    - more_itertools
    - open3d
    - torch-ema==0.3
    - PyMCubes
    - pysdf
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
    - h5py
    - einops
    - ema_pytorch==0.0.10
    - accelerate
    - tensorboard==2.10.1
    - lpips==0.1.4
    - scikit-image==0.19
